name: Cypress Tests

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to test"
        required: false

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run e2e Tests
        env:
          CYPRESS_USERNAME: ${{ secrets.USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.PASSWORD }}
        run: npm run test:full

      - name: Upload Mochawesome Reports as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mochawesome-reports
          path: cypress/reports
